version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: amber-home-db
    environment:
      POSTGRES_DB: amber_home
      POSTGRES_USER: amber_user
      POSTGRES_PASSWORD: amber_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amber_user -d amber_home"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: