version: '3.8'

services:
  datacollector:
    build: .
    container_name: amber-datacollector-service
    environment:
      # Database connection - uses Railway DATABASE_URL if set,
      # otherwise uses local postgres URL from parent project
      DATABASE_URL: ${DATABASE_URL}
      
      # Amber API configuration
      AMBER_API_KEY: ${AMBER_API_KEY}
      
      # Required configuration
      HISTORICAL_START_DATE: ${HISTORICAL_START_DATE}
      
      # Optional configuration (with defaults)
      COLLECTION_INTERVAL_MINUTES: ${COLLECTION_INTERVAL_MINUTES:-5}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      FORCE_REINIT: ${FORCE_REINIT:-false}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M